### ISSUE TITLE
influence spreading process

### ISSUE THREAD

**Issue by kinjal20** [smaniu/oim#5]
When initially algorithm selects some of the nodes as seed node then what happen in a network so that influence starts to spread? how can we estimate total influence at the end? May I give seed node input from other file or use my own seed node set?

**Comment by smaniu** [comment]
> When initially algorithm selects some of the nodes as seed node then what happen in a network so that influence starts to spread? 

We apply it using some of the evaluators (interfaced in Evaluator.hpp) and then a trial is done using one of the samplers (interfaced in Sampler.hpp).

> how can we estimate total influence at the end? 

By simply counting the influenced nodes from a trial returned from Sampler.hpp.

> May I give seed node input from other file or use my own seed node set?

Yes by using the influence simulators directly (passing the seeds in the .trial method of the Sampler). To use this, you will have to modify the code yourself.

**Comment by kinjal20** [comment]
Thank you. May you provide me your paper so that I can give it as reference ?

**Comment by smaniu** [comment]
>  May you provide me your paper so that I can give it as reference ?

There are links to the papers in the README.md
